language: python

python:
    - 2.7

install:
    - sudo apt-get update
    - sudo apt-get install -q -y python-software-properties
    - sudo add-apt-repository -y ppa:scilifelab/scilifelab
    - sudo add-apt-repository -y ppa:debian-med/ppa
    - sudo apt-get update
    - sudo apt-get purge python-paramiko
    - sudo apt-get install -q -y git-core gcc libsam-java=1.74-1ubuntu1 picard-tools=1.74-1ubuntu1 bowtie bwa freebayes snpeff-2 fastqc-0.10.1 gatk r-base tophat openjdk-6-jre samtools unzip lftp cufflinks wigtools python-dev
    #Download snpeff gnome database
    - lftp -e 'pget -n 8 http://downloads.sourceforge.net/project/snpeff/databases/v2_0_5/snpEff_v2_0_5_GRCh37.63.zip; quit'
    - sudo unzip snpEff_v2_0_5_GRCh37.63.zip -d /usr/share/snpEff/ && rm snpEff_v2_0_5_GRCh37.63.zip 
    #Temporal solution to travis issue #155
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
    - pip install numpy
    - pip install cython
    - pip install pysam==0.7
    - cd nextgen && python setup.py install

notifications:
    email: false

before_script:
    - cd tests
    #Export some environment variables
    - export PICARD_HOME=/usr/share/java/picard
    - export SNPEFF_HOME=/usr/share/java/snpeff
    - export GATK_HOME=/usr/share/java/gatk

script: nosetests -s -v --with-xunit -a standard
